/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  registry: {
    CollectionIds: () => import('#modules/_registry/collection_ids'),
    definitions: {
      Courier: () => import('#modules/_registry/definitions/courier'),
      Directory: () => import('#modules/_registry/definitions/directory'),
    },
    ModuleRegistry: () => import('#modules/_registry/module_registry'),
    ProvisioningService: () => import('#modules/_registry/provisioning_service'),
    Types: () => import('#modules/_registry/types'),
  },
  admin: {
    AdminMarketplace: () => import('#modules/admin/admin_marketplace_controller'),
  },
  auth: {
    Auth: () => import('#modules/auth/auth_controller'),
    AuthService: () => import('#modules/auth/auth_service'),
    AuthValidator: () => import('#modules/auth/auth_validator'),
  },
  courier: {
    Courier: () => import('#modules/courier/courier_controller'),
    CourierEnums: () => import('#modules/courier/courier_enums'),
    CourierService: () => import('#modules/courier/courier_service'),
    CourierValidator: () => import('#modules/courier/courier_validator'),
  },
  directory: {
    DepartmentMembers: () => import('#modules/directory/department_members_controller'),
    Departments: () => import('#modules/directory/departments_controller'),
    DepartmentsService: () => import('#modules/directory/departments_service'),
    DepartmentsValidator: () => import('#modules/directory/departments_validator'),
    MembersService: () => import('#modules/directory/members_service'),
    MembersValidator: () => import('#modules/directory/members_validator'),
  },
  organisations: {
    Members: () => import('#modules/organisations/members_controller'),
    OrganisationModules: () => import('#modules/organisations/organisation_modules_controller'),
    OrganisationService: () => import('#modules/organisations/organisation_service'),
    OrganisationValidator: () => import('#modules/organisations/organisation_validator'),
    Organisations: () => import('#modules/organisations/organisations_controller'),
  },
}
