import { Collections } from '#modules/_registry/collection_ids'
import {
  CourierCustodyState,
  CourierStatus,
  CourierStructureType,
  CourierType,
  CourierUrgency,
} from '#modules/courier/courier_enums'
import { Permission, Role } from 'node-appwrite'
import { type ModuleDefinition } from '../types.js'

export const courierModule: ModuleDefinition = {
  name: 'courier',
  label: 'Courier Management',
  description:
    'Manage incoming, outgoing, and internal couriers, assignments, file attachments, and external contacts.',
  core: false,
  collections: [
    {
      id: Collections.COURIERS,
      name: 'Couriers',
      documentSecurity: true,
      permissions: (orgId: string) => [
        Permission.read(Role.team(orgId)),
        Permission.create(Role.team(orgId)),
        Permission.update(Role.team(orgId)),
        Permission.delete(Role.team(orgId, 'admin')),
      ],
      attributes: [
        {
          key: 'type',
          type: 'enum',
          elements: Object.values(CourierType),
          required: true,
          default: CourierType.INCOMING,
        },
        {
          key: 'urgency',
          type: 'enum',
          elements: Object.values(CourierUrgency),
          required: true,
          default: CourierUrgency.NORMAL,
        },
        { key: 'subject', type: 'string', size: 255, required: true },
        { key: 'receivedAt', type: 'datetime', required: false },
        { key: 'emittedAt', type: 'datetime', required: false },
        { key: 'delivererName', type: 'string', size: 255, required: false },
        { key: 'delivererEmail', type: 'string', size: 255, required: false },
        { key: 'delivererPhone', type: 'string', size: 255, required: false },
        { key: 'correspondentId', type: 'string', size: 36, required: false },
        { key: 'internalEntityId', type: 'string', size: 36, required: false }, // @deprecated — use courier_assignments collection
        {
          key: 'targetType',
          type: 'enum',
          elements: ['user', 'department'],
          required: false,
        },
        { key: 'fileIds', type: 'string', size: 36, required: false, array: true },
        { key: 'createdBy', type: 'string', size: 36, required: true },
        {
          key: 'status',
          type: 'enum',
          elements: Object.values(CourierStatus),
          required: true,
          default: CourierStatus.PENDING,
        },
        { key: 'isFavorite', type: 'boolean', required: true, default: false },
        { key: 'isArchived', type: 'boolean', required: true, default: false },
        { key: 'isDeleted', type: 'boolean', required: true, default: false },
        { key: 'requiresPickup', type: 'boolean', required: false, default: false },
        { key: 'pickedUpAt', type: 'datetime', required: false },
        { key: 'pickedUpBy', type: 'string', size: 36, required: false },
        {
          key: 'currentCustody',
          type: 'enum',
          elements: Object.values(CourierCustodyState),
          required: false,
          default: CourierCustodyState.COURIER_SERVICE,
        },
        { key: 'custodyUserId', type: 'string', size: 36, required: false },
        { key: 'custodyDeptId', type: 'string', size: 36, required: false },
        { key: 'signedProofFileId', type: 'string', size: 36, required: false },
        { key: 'dispatchedAt', type: 'datetime', required: false },
        { key: 'dispatchedBy', type: 'string', size: 36, required: false },
        { key: 'receivedAt', type: 'datetime', required: false },
        { key: 'receivedBy', type: 'string', size: 36, required: false },
        { key: 'handlerUserId', type: 'string', size: 36, required: false },
        { key: 'replyCount', type: 'integer', required: true, default: 0 },
      ],
      indexes: [
        { key: 'subject_idx', type: 'key', attributes: ['subject'] },
        { key: 'correspondent_idx', type: 'key', attributes: ['correspondentId'] },
        { key: 'internal_entity_idx', type: 'key', attributes: ['internalEntityId'] },
        { key: 'creator_idx', type: 'key', attributes: ['createdBy'] },
        { key: 'status_idx', type: 'key', attributes: ['status'] },
        { key: 'archived_idx', type: 'key', attributes: ['isArchived'] },
        { key: 'favorite_idx', type: 'key', attributes: ['isFavorite'] },
        { key: 'deleted_idx', type: 'key', attributes: ['isDeleted'] },
        { key: 'custody_idx', type: 'key', attributes: ['currentCustody'] },
      ],
    },
    {
      id: Collections.COURIER_ASSIGNMENTS,
      name: 'Courier Assignments',
      documentSecurity: true,
      permissions: (orgId: string) => [
        Permission.read(Role.team(orgId)),
        Permission.create(Role.team(orgId)),
        Permission.update(Role.team(orgId)),
        Permission.delete(Role.team(orgId, 'admin')),
      ],
      attributes: [
        { key: 'courierId', type: 'string', size: 36, required: true },
        { key: 'entityId', type: 'string', size: 36, required: true },
        {
          key: 'entityType',
          type: 'enum',
          elements: ['user', 'department', 'external_contact'],
          required: true,
        },
        { key: 'entityName', type: 'string', size: 255, required: false },
        { key: 'assignedBy', type: 'string', size: 36, required: true },
      ],
      indexes: [
        { key: 'courier_idx', type: 'key', attributes: ['courierId'] },
        { key: 'entity_idx', type: 'key', attributes: ['entityId'] },
        { key: 'entity_type_idx', type: 'key', attributes: ['entityId', 'entityType'] },
      ],
    },
    {
      id: Collections.EXTERNAL_CONTACTS,
      name: 'External Contacts',
      documentSecurity: true,
      permissions: (orgId: string) => [
        Permission.read(Role.team(orgId)),
        Permission.create(Role.team(orgId)),
        Permission.update(Role.team(orgId)),
        Permission.delete(Role.team(orgId, 'admin')),
      ],
      attributes: [
        { key: 'name', type: 'string', size: 255, required: true },
        { key: 'email', type: 'string', size: 255, required: false },
        { key: 'phone', type: 'string', size: 255, required: false },
        {
          key: 'structureType',
          type: 'enum',
          elements: Object.values(CourierStructureType),
          required: true,
        },
        { key: 'idNumber', type: 'string', size: 255, required: false },
        { key: 'address', type: 'string', size: 500, required: false },
        { key: 'createdBy', type: 'string', size: 36, required: true },
      ],
      indexes: [
        { key: 'name_idx', type: 'key', attributes: ['name'] },
        { key: 'structure_type_idx', type: 'key', attributes: ['structureType'] },
        { key: 'creator_idx', type: 'key', attributes: ['createdBy'] },
      ],
    },
    {
      id: Collections.COURIER_REPLIES,
      name: 'Courier Replies',
      documentSecurity: true,
      permissions: (orgId: string) => [
        Permission.read(Role.team(orgId)),
        Permission.create(Role.team(orgId)),
        Permission.update(Role.team(orgId)),
        Permission.delete(Role.team(orgId, 'admin')),
      ],
      attributes: [
        { key: 'courierId', type: 'string', size: 36, required: true },
        { key: 'subject', type: 'string', size: 255, required: false },
        { key: 'content', type: 'string', size: 10000, required: false },
        { key: 'notes', type: 'string', size: 2000, required: false },
        { key: 'fileId', type: 'string', size: 36, required: false },
        { key: 'emittedAt', type: 'datetime', required: false },
        { key: 'fileIds', type: 'string', size: 36, required: false, array: true },
        { key: 'delivererName', type: 'string', size: 255, required: false },
        { key: 'delivererEmail', type: 'string', size: 255, required: false },
        { key: 'delivererPhone', type: 'string', size: 255, required: false },
        { key: 'note', type: 'string', size: 2000, required: false },
        { key: 'createdBy', type: 'string', size: 36, required: true },
        { key: 'createdAt', type: 'datetime', required: true, default: new Date() },
      ],
      indexes: [
        { key: 'courier_idx', type: 'key', attributes: ['courierId'] },
        { key: 'creator_idx', type: 'key', attributes: ['createdBy'] },
      ],
    },
    {
      id: Collections.COURIER_MESSAGES,
      name: 'Courier Messages',
      documentSecurity: true,
      permissions: (orgId: string) => [
        Permission.read(Role.team(orgId)),
        Permission.create(Role.team(orgId)),
        Permission.update(Role.team(orgId)),
        Permission.delete(Role.team(orgId, 'admin')),
      ],
      attributes: [
        { key: 'courierId', type: 'string', size: 36, required: true },
        { key: 'content', type: 'string', size: 5000, required: true },
        { key: 'fileId', type: 'string', size: 36, required: false },
        { key: 'createdBy', type: 'string', size: 36, required: true },
        { key: 'createdAt', type: 'datetime', required: true, default: new Date() },
      ],
      indexes: [{ key: 'courier_idx', type: 'key', attributes: ['courierId'] }],
    },
    {
      id: Collections.COURIER_ACTIVITIES,
      name: 'Courier Activities',
      documentSecurity: true,
      permissions: (orgId: string) => [
        Permission.read(Role.team(orgId)),
        Permission.create(Role.team(orgId)),
        Permission.update(Role.team(orgId)),
        Permission.delete(Role.team(orgId, 'admin')),
      ],
      attributes: [
        { key: 'courierId', type: 'string', size: 36, required: true },
        {
          key: 'action',
          type: 'enum',
          elements: [
            'created',
            'updated',
            'assigned',
            'picked_up',
            'handed_over',
            'dispatched',
            'status_changed',
            'archived',
            'restored',
            'deleted',
            'replied',
            'handler_assigned',
          ],
          required: true,
        },
        { key: 'performedBy', type: 'string', size: 36, required: true },
        { key: 'details', type: 'string', size: 2000, required: false },
        { key: 'createdAt', type: 'datetime', required: true },
      ],
      indexes: [
        { key: 'courier_idx', type: 'key', attributes: ['courierId'] },
        { key: 'performer_idx', type: 'key', attributes: ['performedBy'] },
      ],
    },
    {
      id: Collections.COURIER_USER_STATES,
      name: 'Courier User States',
      documentSecurity: true,
      permissions: (orgId: string) => [
        Permission.read(Role.team(orgId)),
        Permission.create(Role.team(orgId)),
        Permission.update(Role.team(orgId)),
        Permission.delete(Role.team(orgId, 'admin')),
      ],
      attributes: [
        { key: 'courierId', type: 'string', size: 36, required: true },
        { key: 'userId', type: 'string', size: 36, required: true },
        { key: 'isOpened', type: 'boolean', required: true, default: false },
        { key: 'isListed', type: 'boolean', required: true, default: false },
      ],
      indexes: [
        { key: 'courier_user_idx', type: 'key', attributes: ['courierId', 'userId'] },
        { key: 'user_idx', type: 'key', attributes: ['userId'] },
      ],
    },
  ],
}
