import { Permission, Role } from 'node-appwrite'
import { type ModuleDefinition } from '../types.js'
import {
  CourierUrgency,
  CourierStatus,
  CourierType,
  CourierStructureType,
  DocumentStatus,
} from '#modules/courier/courier_enums'
import { Collections } from '#modules/_registry/collection_ids'

export const courierModule: ModuleDefinition = {
  name: 'courier',
  label: 'Courier Management',
  description:
    'Manage incoming, outgoing, and internal couriers, assignments, file attachments, and external contacts.',
  core: false,
  collections: [
    {
      id: Collections.COURIERS,
      name: 'Couriers',
      documentSecurity: true,
      permissions: (orgId: string) => [
        Permission.read(Role.team(orgId)),
        Permission.create(Role.team(orgId)),
        Permission.update(Role.team(orgId)),
        Permission.delete(Role.team(orgId, 'admin')),
      ],
      attributes: [
        {
          key: 'type',
          type: 'enum',
          elements: Object.values(CourierType),
          required: true,
          default: CourierType.INCOMING,
        },
        {
          key: 'urgency',
          type: 'enum',
          elements: Object.values(CourierUrgency),
          required: true,
          default: CourierUrgency.NORMAL,
        },
        { key: 'subject', type: 'string', size: 255, required: true },
        { key: 'receivedAt', type: 'datetime', required: false },
        { key: 'emittedAt', type: 'datetime', required: false },
        { key: 'senderName', type: 'string', size: 255, required: false },
        { key: 'senderEmail', type: 'string', size: 255, required: false },
        { key: 'senderPhone', type: 'string', size: 255, required: false },
        { key: 'externalContactId', type: 'string', size: 36, required: false },
        {
          key: 'externalContactType',
          type: 'enum',
          elements: Object.values(CourierStructureType),
          required: false,
        },
        { key: 'internalEntityId', type: 'string', size: 36, required: false }, // @deprecated — use courier_assignments collection
        {
          key: 'targetType',
          type: 'enum',
          elements: ['user', 'department'],
          required: false,
        },
        { key: 'fileId', type: 'string', size: 36, required: false },
        { key: 'createdBy', type: 'string', size: 36, required: true },
        {
          key: 'status',
          type: 'enum',
          elements: Object.values(CourierStatus),
          required: true,
          default: CourierStatus.PENDING,
        },
        { key: 'isFavorite', type: 'boolean', required: true, default: false },
        { key: 'isArchived', type: 'boolean', required: true, default: false },
        { key: 'isDeleted', type: 'boolean', required: true, default: false },
        { key: 'requiresPickup', type: 'boolean', required: false, default: false },
        { key: 'pickedUpAt', type: 'datetime', required: false },
        { key: 'pickedUpBy', type: 'string', size: 36, required: false },
        { key: 'replyCount', type: 'integer', required: true, default: 0 },
      ],
      indexes: [
        { key: 'subject_idx', type: 'key', attributes: ['subject'] },
        { key: 'external_contact_idx', type: 'key', attributes: ['externalContactId'] },
        { key: 'internal_entity_idx', type: 'key', attributes: ['internalEntityId'] },
        { key: 'creator_idx', type: 'key', attributes: ['createdBy'] },
        { key: 'status_idx', type: 'key', attributes: ['status'] },
        { key: 'archived_idx', type: 'key', attributes: ['isArchived'] },
        { key: 'favorite_idx', type: 'key', attributes: ['isFavorite'] },
        { key: 'deleted_idx', type: 'key', attributes: ['isDeleted'] },
      ],
    },
    {
      id: Collections.COURIER_ASSIGNMENTS,
      name: 'Courier Assignments',
      documentSecurity: true,
      permissions: (orgId: string) => [
        Permission.read(Role.team(orgId)),
        Permission.create(Role.team(orgId)),
        Permission.update(Role.team(orgId)),
        Permission.delete(Role.team(orgId, 'admin')),
      ],
      attributes: [
        { key: 'courierId', type: 'string', size: 36, required: true },
        { key: 'entityId', type: 'string', size: 36, required: true },
        {
          key: 'entityType',
          type: 'enum',
          elements: ['user', 'department'],
          required: true,
        },
        { key: 'assignedBy', type: 'string', size: 36, required: true },
      ],
      indexes: [
        { key: 'courier_idx', type: 'key', attributes: ['courierId'] },
        { key: 'entity_idx', type: 'key', attributes: ['entityId'] },
        { key: 'entity_type_idx', type: 'key', attributes: ['entityId', 'entityType'] },
      ],
    },
    {
      id: Collections.EXTERNAL_CONTACTS,
      name: 'External Contacts',
      documentSecurity: true,
      permissions: (orgId: string) => [
        Permission.read(Role.team(orgId)),
        Permission.create(Role.team(orgId)),
        Permission.update(Role.team(orgId)),
        Permission.delete(Role.team(orgId, 'admin')),
      ],
      attributes: [
        { key: 'name', type: 'string', size: 255, required: true },
        { key: 'email', type: 'string', size: 255, required: false },
        { key: 'phone', type: 'string', size: 255, required: false },
        {
          key: 'structureType',
          type: 'enum',
          elements: Object.values(CourierStructureType),
          required: true,
        },
        { key: 'idNumber', type: 'string', size: 255, required: false },
        { key: 'address', type: 'string', size: 500, required: false },
        { key: 'createdBy', type: 'string', size: 36, required: true },
      ],
      indexes: [
        { key: 'name_idx', type: 'key', attributes: ['name'] },
        { key: 'structure_type_idx', type: 'key', attributes: ['structureType'] },
        { key: 'creator_idx', type: 'key', attributes: ['createdBy'] },
      ],
    },
    {
      id: Collections.COURIER_REPLIES,
      name: 'Courier Replies',
      documentSecurity: true,
      permissions: (orgId: string) => [
        Permission.read(Role.team(orgId)),
        Permission.create(Role.team(orgId)),
        Permission.update(Role.team(orgId)),
        Permission.delete(Role.team(orgId, 'admin')),
      ],
      attributes: [
        { key: 'courierId', type: 'string', size: 36, required: true },
        { key: 'content', type: 'string', size: 10000, required: true },
        { key: 'fileId', type: 'string', size: 36, required: false },
        { key: 'createdBy', type: 'string', size: 36, required: true },
        { key: 'createdAt', type: 'datetime', required: true, default: new Date() },
        {
          key: 'documentStatus',
          type: 'enum',
          elements: Object.values(DocumentStatus),
          required: true,
          default: DocumentStatus.DRAFT,
        },
      ],
      indexes: [
        { key: 'courier_idx', type: 'key', attributes: ['courierId'] },
        { key: 'creator_idx', type: 'key', attributes: ['createdBy'] },
      ],
    },
    {
      id: Collections.COURIER_MESSAGES,
      name: 'Courier Messages',
      documentSecurity: true,
      permissions: (orgId: string) => [
        Permission.read(Role.team(orgId)),
        Permission.create(Role.team(orgId)),
        Permission.update(Role.team(orgId)),
        Permission.delete(Role.team(orgId, 'admin')),
      ],
      attributes: [
        { key: 'courierId', type: 'string', size: 36, required: true },
        { key: 'content', type: 'string', size: 5000, required: true },
        { key: 'fileId', type: 'string', size: 36, required: false },
        { key: 'createdBy', type: 'string', size: 36, required: true },
        { key: 'createdAt', type: 'datetime', required: true, default: new Date() },
      ],
      indexes: [{ key: 'courier_idx', type: 'key', attributes: ['courierId'] }],
    },
  ],
}
