name: Deploy Backend to Cloud Run

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: courier-management-501610
  REGION: europe-west1
  REPOSITORY: courier-api
  IMAGE: courier-api
  SERVICE: courier-api

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v3
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}

      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v3

      - name: Set GCP Project
        run: |
          gcloud config set project ${{ env.PROJECT_ID }}

      - name: Docker Authentication
        run: |
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

      - name: Build Docker Image
        run: |
          docker build \
            -t ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE }}:${{ github.sha }} .

      - name: Push Docker Image
        run: |
          docker push \
            ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE }}:${{ github.sha }}

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ env.SERVICE }} \
            --image=${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE }}:${{ github.sha }} \
            --region=${{ env.REGION }} \
            --platform=managed \
            --service-account=cloudrun-sa@courier-management-501610.iam.gserviceaccount.com \
            --memory=512Mi \
            --min-instances=0 \
            --max-instances=2 \
            --no-allow-unauthenticated \
            --set-env-vars="NODE_ENV=production,TZ=UTC,LOG_LEVEL=info,LOCK_STORE=redis,LIMITER_STORE=redis,APP_KEY=${{ secrets.APP_KEY }},APP_URL=${{ secrets.APP_URL }},APPWRITE_ENDPOINT=${{ secrets.APPWRITE_ENDPOINT }},APPWRITE_PROJECT_ID=${{ secrets.APPWRITE_PROJECT_ID }},APPWRITE_KEY=${{ secrets.APPWRITE_KEY }},TEMP_MEMBER_PASSWORD=${{ secrets.TEMP_MEMBER_PASSWORD }},REDIS_HOST=${{ secrets.REDIS_HOST }},REDIS_PORT=${{ secrets.REDIS_PORT }},REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }},RESEND_API_KEY=${{ secrets.RESEND_API_KEY }},MAIL_FROM_ADDRESS=${{ secrets.MAIL_FROM_ADDRESS }},REDIS_KEY_PREFIX=${{ secrets.REDIS_KEY_PREFIX }}" 


